### PR TITLE
Add information that Trustroots Foundation is dissolved.

### LINKED ISSUE #2585: Information about Trustroots Foundation is not accurate any more
As of March 2022 [Trustroots Foundation has been dissolved](https://find-and-update.company-information.service.gov.uk/company/09489825/filing-history). While we still try to find out what exactly it means for the community, we need to update the website with more accurate information.

Proposed changes:
- [x] Add a note at the top of the [Foundation](https://www.trustroots.org/foundation) page:
   > As of May 2022 [Trustroots Foundation has been dissolved](https://find-and-update.company-information.service.gov.uk/company/09489825/filing-history). We still try to find out what exactly it means for the community.
- [x] Add a paragraph at the beginning of [FAQ: Foundation - What's your legal status?](https://www.trustroots.org/faq/foundation#what-is-your-legal-status) question:
   > As of May 2022 [Trustroots Foundation has been dissolved](https://find-and-update.company-information.service.gov.uk/company/09489825/filing-history). What does it mean for the community? We don't know exactly yet!
- [x] Remove [FAQ: Foundation - Who are the board?](https://www.trustroots.org/faq/foundation#who-are-the-board) question and answer.
- [ ] maybe: Update [front page](https://www.trustroots.org/), at the moment it states:
  > Owned and operated by Trustroots Foundation, a non-profit registered in the United Kingdom since March 2015.
- [ ] maybe: Review and rename _Foundation_ to _Organization_
  - [ ] [Foundation FAQ](https://www.trustroots.org/faq/foundation), links and path `/faq/foundation` -> `/faq/organization`
  - [ ] Selected links to the [Foundation](https://www.trustroots.org/foundation) page
  - [ ] Mentions of _the foundation_ in the texts

### PR DESCRIPTION
**Pull request by mariha**
This change:
* Adds a note at the top of the [Foundation](https://www.trustroots.org/foundation) page:
  > As of March 2022 [Trustroots Foundation has been dissolved](https://find-and-update.company-information.service.gov.uk/company/09489825/filing-history). We still try to find out what exactly it means for the community.

* Adds a paragraph at the beginning of [FAQ: Foundation - What's your legal status?](https://www.trustroots.org/faq/foundation#what-is-your-legal-status) question:
  > As of March 2022 [Trustroots Foundation has been dissolved](https://find-and-update.company-information.service.gov.uk/company/09489825/filing-history). What does it mean for the community? We don't know exactly yet!

* Removes [FAQ: Foundation - Who are the board?](https://www.trustroots.org/faq/foundation#who-are-the-board) question and answer.

* Removes WarmShowers as a good example to follow.

Fixes #2585

### CODE REVIEW

**Review by mrkvon — APPROVED** [review]
LGTM

would be nice to be able to merge and deploy stuff...

**Comment by mrkvon** [comment]
btw not sure if we need to extract the translation strings. According to [our i18n docs](https://github.com/Trustroots/trustroots/blob/eb99f11b428347cf9837f21f29cfc085ec4b92e1/docs/i18n.md#4-enjoy), they'll get extracted when we merge this to master.

Not sure if that still works though. In any case, manual extraction won't do any harm... :)

**Comment by chmac** [comment]
I'm opposed to merging this until a valid rationale has been shared in #2585.

**Comment by mariha** [comment]
@mrkvon Given that #2587 had to be done, extract-i18n is not run (successfully).

I created #2589 to fix it.

**Comment by mrkvon** [comment]
Mergeable by non-owners. Progress discussion? Merge?

**Comment by mariha** [comment]
I'm merging it. 

[There was a suggestion](https://github.com/Trustroots/trustroots/issues/2585#issuecomment-1215044605) that the wording may be too provocative, but others didn't confirm, clarify or object. 

As to me, the question is a way to express our, volunteers team members, insecurities. 

At this point (1,5 month after making a PR) I guess I just would really like to move forward and close this, but if others felt the wording is really very bad, please submit a follow-up PR, I'll be happy to review and approve it. I may also do it myself in a free time.

**Comment by mrkvon** [comment]
Bold move! 🎉

> please _submit a follow-up PR_, I'll be happy to _review_ and _approve_ it

_(emphasis mine)_ Sounds like a good process! Cheers to doocracy and transparency! 🙂

**Pull request merged**
