### PR TITLE
fixed a typo in Readme

### PR DESCRIPTION
**Pull request by Fawwad-Khan**
#### Proposed Changes

*

#### Testing Instructions

*

Fixes #

### CODE REVIEW

**Comment by Fawwad-Khan** [comment]
In the first or second line maybe
It was
"you don't need the be a programmer to"
Changed it to
"You don't need to be a programmer to"

**Comment by guaka** [comment]
But I see changes in 5 different parts. If you only fix one type, it's good to just change one line.

**Comment by Fawwad-Khan** [comment]
I just cloned and changed one line, I'm really sorry if I screwed it up or
anything

**Comment by guaka** [comment]
It's not a big deal :) I still need to learn a lot about `git` myself.

See https://github.com/Trustroots/trustroots/pull/771/commits/c5cf144ced857b752d4231957c3b39b40cdbae05

Wanna try to revert (I think `git reset --hard HEAD` can do the trick) and try again?

**Comment by Fawwad-Khan** [comment]
Okay I'll try again, I'm fairly new to git, just starting to contribute

**Comment by Fawwad-Khan** [comment]
Hey, I just checked, the prettier extension just removed some spaces and stuff in the file, so I think its not that different, from the original

**Pull request merged**
