### PR TITLE
Move away from require with path.resolve().

### PR DESCRIPTION
**Pull request by mariha**
The jscodeshift code used for the transformation:

```js
const path = require('path');

export default function transformer(file, api) {
  const j = api.jscodeshift;

  return j(file.source)
    .find(j.CallExpression, {callee: {type: "Identifier", name: "require"}})
    .filter(callExpr => {  // has path.resolve() as an argument
      return callExpr.value.arguments[0].type === "CallExpression" // call expression (not a literal)
        && callExpr.value.arguments[0].callee.property.name === "resolve"
        && callExpr.value.arguments[0].arguments[0].type === "Literal";
    })
    .forEach(callExpr => {
      const originalPath = callExpr.value.arguments[0].arguments[0].value;
      const absolutePath = path.resolve(originalPath);
      const relativePath = path.relative(path.dirname(file.path), absolutePath);

      // files from the same directory resulted in 'Error: Cannot find module' if './' was not added
      callExpr.value.arguments[0] = j.literal(relativePath.startsWith('.') ? relativePath : "./" + relativePath);
    })
    .toSource({quote: 'single'});
}
```

A step towards #2486

### CODE REVIEW

**Review by simison — APPROVED** [review]
Great job with this! I've smoke tested different things, including email notifications, and things are working smoothly.

There will likely be a couple of cases we need to sort out manually when moving to `imports` but that can be done in separate PR. (I searched for `require(path.resolve` and see 6 cases).

Linter check in this PR is failing because of a fork but ran it locally (`npm run lint`) and it passed.

**Comment by mariha** [comment]
> Linter check in this PR is failing because of a fork but ran it locally (npm run lint) and it passed.
For whatever reason I can not push changes/create branch directly to TR repo.

**Comment by mariha** [comment]
There are a few more `require('path')`, haven't looked into them.

```zsh
➜  trustroots grep -rn "require('path')" . 
./bin/generate-circle-images.js:15:const path = require('path');
./config/config.js:8:const path = require('path');
./config/webpack/templateloader.js:1:const { join, resolve } = require('path');
./config/webpack/webpack.config.js:17:const { join, resolve } = require('path');
./config/webpack/webpack.shims.js:20:const { join } = require('path');
./config/webpack/webpack.push-messaging-sw.config.js:1:const { join } = require('path');
./config/lib/express.js:21:const path = require('path');
./config/lib/mongoose.js:6:const path = require('path');
./scripts/exportEmailsAsEml.js:14:var path = require('path'),
./modules/core/tests/server/jobs/send-push-message.server.job.tests.js:3:const path = require('path');
./modules/core/server/services/email.server.service.js:5:const path = require('path');
./modules/users/tests/server/user-removal.server.routes.tests.js:6:const path = require('path');
./modules/users/server/config/users.config.server.js:6:const path = require('path');
./modules/users/server/controllers/users.profile.server.controller.js:5:const path = require('path');
./modules/users/server/controllers/users.avatar.server.controller.js:6:const path = require('path');
```

**Comment by simison** [comment]
I sent an invite to join the Trustroots repo, you should have it in email and somewhere in github interface, maybe at https://github.com/Trustroots/

**Comment by simison** [comment]
Yep, those might also be valid reasons to use `path`, so they will just need to be converted into `import`s.

**Pull request merged**
