### PR TITLE
Update to Mongoose v5

### LINKED ISSUE #580: Upgrade compatibility with MongoDB 3.6
Mostly just aggregate queries that need updating ('cursor' option is required for those).

Mongoose update would be good as well (#539)

### PR DESCRIPTION
**Pull request by simison**
2nd try of https://github.com/Trustroots/trustroots/pull/634 which I reverted in https://github.com/Trustroots/trustroots/pull/658 because of `UnhandledPromiseRejectionWarning`/`MongoError`:

```
Mongoose: users.find({ roles: { '$elemMatch': { '$ne': 'suspended' } }, welcomeSequenceSent: { '$lt': new Date("Sun, 12 Aug 2018 19:29:12 GMT") }, welcomeSequenceStep: 2, public: true }, { limit: 50, fields: {} })
(node:27573) UnhandledPromiseRejectionWarning: MongoError: The 'cursor' option is required, except for aggregate with the explain argument
    at Function.MongoError.create (/Users/mikael/Documents/trustroots/node_modules/mongoose/node_modules/mongodb-core/lib/error.js:31:11)
    at /Users/mikael/Documents/trustroots/node_modules/mongoose/node_modules/mongodb-core/lib/connection/pool.js:489:72
    at authenticateStragglers (/Users/mikael/Documents/trustroots/node_modules/mongoose/node_modules/mongodb-core/lib/connection/pool.js:435:16)
    at Connection.messageHandler (/Users/mikael/Documents/trustroots/node_modules/mongoose/node_modules/mongodb-core/lib/connection/pool.js:469:5)
    at Socket.<anonymous> (/Users/mikael/Documents/trustroots/node_modules/mongoose/node_modules/mongodb-core/lib/connection/connection.js:321:22)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at TCP.onread (net.js:639:20)
(node:27573) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:27573) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[Worker] Agenda job [welcome sequence first] 59b0fd4bf0bad605b73f1636 finished.
[Worker] Agenda job [check unread messages] 59b0fd4bf0bad605b73f162c failed with [The 'cursor' option is required, except for aggregate with the explain argument]  failCount:2
```

Resolves #580

### CODE REVIEW

**Comment by simison** [comment]
Just rebased this with latest master :thumbsup:

**Comment by mrkvon** [comment]
Hello, do we have any update on this PR? Is there something that needs to be done in order to have this approved and merged?
The error was, in my opinion, caused by non-upgraded libraries. Wasn't it?

**Comment by guaka** [comment]
@Akronix and I are trying this on my machine now.

We're getting:

```
MongoDB version: 3.4.9
MongoDB version incompatibility! Compatible version(s): >=3.6 <=4.0
[Server] Script crashed.
```

We're looking into this now.

**Comment by mrkvon** [comment]
The error is caused by [this line in package.json](https://github.com/Trustroots/trustroots/pull/659/files#diff-b9cfc7f2cdf78a7f4b91a753d10865a2L14).
This is supposed to work with the mongodb 3.6+. This PR specifically solves the upgrading problem.
All my tests are passing with mongo v4.0.2, so this version could be fine, too.
I'm not sure what exactly should be there in [package.json](https://github.com/Trustroots/trustroots/pull/659/files#diff-b9cfc7f2cdf78a7f4b91a753d10865a2L14). Perhaps higher versions of mongodb would be fine, too.

**Comment by simison** [comment]
Spinning this up on MongoDB 3.6, I get:

>the server/replset/mongos/db options are deprecated, all their options are supported at the top level of the options object [poolSize,ssl,sslValidate,sslCA,sslCert,sslKey,sslPass,sslCRL,autoReconnect,noDelay,keepAlive,keepAliveInitialDelay,connectTimeoutMS,family,socketTimeoutMS,reconnectTries,reconnectInterval,ha,haInterval,replicaSet,secondaryAcceptableLatencyMS,acceptableLatencyMS,connectWithNoPrimary,authSource,w,wtimeout,j,forceServerObjectId,serializeFunctions,ignoreUndefined,raw,bufferMaxEntries,readPreference,pkFactory,promiseLibrary,readConcern,maxStalenessSeconds,loggerLevel,logger,promoteValues,promoteBuffers,promoteLongs,domainsEnabled,checkServerIdentity,validateOptions,appname,auth,user,password,authMechanism,compression,fsync,readPreferenceTags,numberOfRetries,auto_reconnect,minSize,monitorCommands,retryWrites,useNewUrlParser]
(node:57952) DeprecationWarning: current URL string parser is deprecated, and will be removed in a future version. To use the new parser, pass option { useNewUrlParser: true } to MongoClient.connect.

For reference: 
https://github.com/Trustroots/trustroots/blob/5e15aa47987fd335fba4fb98aaf5503cec3e73b9/config/env/development.js#L14-L27

**Comment by simison** [comment]
Tested this a bit more and didn't find issues — going to give another shot. 🤞

**Comment by mrkvon** [comment]
The mongodb may need to be upgraded in steps: versions 3.4 -> 3.6 -> 4. Not directly 3.4 -> 4.

**Comment by simison** [comment]
Yep, I'm aware. 👍  Thanks for checking.

**Pull request merged**
