### PR TITLE
Revert "minimal upgrade to mongoose v5"

### PR DESCRIPTION
**Pull request by simison**
Reverts Trustroots/trustroots#634

Seems like we still need some changes in worker scripts, I found this from logs:
```
Mongoose: users.find({ roles: { '$elemMatch': { '$ne': 'suspended' } }, welcomeSequenceSent: { '$lt': new Date("Sun, 12 Aug 2018 19:29:12 GMT") }, welcomeSequenceStep: 2, public: true }, { limit: 50, fields: {} })
(node:27573) UnhandledPromiseRejectionWarning: MongoError: The 'cursor' option is required, except for aggregate with the explain argument
    at Function.MongoError.create (/Users/mikael/Documents/trustroots/node_modules/mongoose/node_modules/mongodb-core/lib/error.js:31:11)
    at /Users/mikael/Documents/trustroots/node_modules/mongoose/node_modules/mongodb-core/lib/connection/pool.js:489:72
    at authenticateStragglers (/Users/mikael/Documents/trustroots/node_modules/mongoose/node_modules/mongodb-core/lib/connection/pool.js:435:16)
    at Connection.messageHandler (/Users/mikael/Documents/trustroots/node_modules/mongoose/node_modules/mongodb-core/lib/connection/pool.js:469:5)
    at Socket.<anonymous> (/Users/mikael/Documents/trustroots/node_modules/mongoose/node_modules/mongodb-core/lib/connection/connection.js:321:22)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at TCP.onread (net.js:639:20)
(node:27573) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:27573) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[Worker] Agenda job [welcome sequence first] 59b0fd4bf0bad605b73f1636 finished.
[Worker] Agenda job [check unread messages] 59b0fd4bf0bad605b73f162c failed with [The 'cursor' option is required, except for aggregate with the explain argument]  failCount:2
```

FYI @mrkvon

### CODE REVIEW

**Comment by mrkvon** [comment]
Ah, that's unfortunate. I'll look into it soon, possibly tomorrow.

**Comment by mrkvon** [comment]
In what context does it appear? How can we reproduce this?
I tried to observe my log for a while, and at least `[Worker] Agenda job [check unread messages]` seems to be successful.

Log excerpt:
```
[Worker] Agenda job [welcome sequence first] 5b7ea25de288db505453a576 finished.
[Worker] Agenda job [send email] 5b83285464ecec15dcc0227e finished.
[Worker] Agenda job [check unread messages] 5b7ea25de288db505453a575 finished.
[Worker] Agenda job [check unread messages] 5b7ea25de288db505453a575 finished.
(node:5470) DeprecationWarning: collection.update is deprecated. Use updateOne, updateMany, or bulkWrite instead.
[Worker] Agenda job [check unread messages] 5b7ea25de288db505453a575 finished.
[Worker] Agenda job [send email] 5b832ab19375d6155e63f08f finished.
```

**Comment by simison** [comment]
I'll re-test this for you tomorrow! I didn't have time to properly dig in.

For easier test you can adjust time from 5min to 30sec or so from
`config/lib/worker.js`

For what's worth; I tested on Mongo 3.6 and Node.js 10.6

**Comment by mrkvon** [comment]
I tested with Mongo 4.0.0 and Node 10.9.0. Seems like some additional ci-tests for worker could be useful.

**Comment by simison** [comment]
Hmm, I just tested and it seemed to work again:
```
[Worker] Agenda job [check unread messages] 59b0fd4bf0bad605b73f162c finished.
Mongoose: users.find({ public: true, welcomeSequenceStep: 0, welcomeSequenceSent: { '$lt': new Date("Mon, 27 Aug 2018 07:10:11 GMT") }, roles: { '$elemMatch': { '$ne': 'suspended' } } }, { limit: 50, fields: {} })
Mongoose: offers.find({ type: 'host', status: 'no', updated: { '$lt': new Date("Tue, 29 May 2018 07:10:11 GMT") }, reactivateReminderSent: { '$exists': false } }, { fields: {} })
[Worker] Agenda job [welcome sequence first] 59b0fd4bf0bad605b73f1636 finished.
[Worker] Agenda job [reactivate hosts] 5a6c88b36bbcf3ed53040af7 finished.
Mongoose: users.find({ public: true, welcomeSequenceStep: 1, welcomeSequenceSent: { '$lt': new Date("Sun, 26 Aug 2018 07:10:11 GMT") }, roles: { '$elemMatch': { '$ne': 'suspended' } } }, { limit: 50, fields: {} })
Mongoose: users.find({ public: false, created: { '$lt': new Date("Mon, 27 Aug 2018 03:10:11 GMT") }, roles: { '$elemMatch': { '$ne': 'suspended' } }, '$and': [ { '$or': [ { publicReminderCount: { '$lt': 3 } }, { publicReminderCount: { '$exists': false } } ] }, { '$or': [ { publicReminderSent: { '$lt': new Date("Sat, 25 Aug 2018 07:10:11 GMT") } }, { publicReminderSent: { '$exists': false } } ] } ] }, { limit: 50, fields: {} })
Mongoose: users.find({ public: true, welcomeSequenceStep: 2, welcomeSequenceSent: { '$lt': new Date("Mon, 13 Aug 2018 07:10:11 GMT") }, roles: { '$elemMatch': { '$ne': 'suspended' } } }, { limit: 50, fields: {} })
[Worker] Agenda job [welcome sequence second] 59b0fd4bf0bad605b73f1637 finished.
[Worker] Agenda job [send signup reminders] 59b0fd4bf0bad605b73f162b finished.
[Worker] Agenda job [welcome sequence third] 59b0fd4bf0bad605b73f163b finished.
Mongoose: messages.aggregate([ { '$match': { read: false, notificationCount: { '$lte': 1 }, created: { '$lt': 2018-08-26T07:10:16.778Z } } }, { '$group': { _id: { userTo: '$userTo', userFrom: '$userFrom' }, total: { '$sum': 1 }, messages: { '$push': { id: '$_id', content: '$content', created: '$created' } }, notificationCount: { '$min': '$notificationCount' } } } ], {})
Mongoose: messages.aggregate([ { '$match': { read: false, notificationCount: { '$lte': 0 }, created: { '$lt': 2018-08-27T07:00:16.782Z } } }, { '$group': { _id: { userTo: '$userTo', userFrom: '$userFrom' }, total: { '$sum': 1 }, messages: { '$push': { id: '$_id', content: '$content', created: '$created' } }, notificationCount: { '$min': '$notificationCount' } } } ], {})
[Worker] Agenda job [check unread messages] 59b0fd4bf0bad605b73f162c finished.
```

Might be I simply had a wrong version of something at NPM modules installed while giving it final test?

**Comment by mrkvon** [comment]
The cursor error happens with an older version of mongoose. Could that be it?

Should we test or observe further?

**Comment by simison** [comment]
Sounds like a likely reason! I was switching between branches and might've just forgot to hit `npm i` again at some point.

**Comment by simison** [comment]
Looks like there were some differences in package-lock, updated in https://github.com/Trustroots/trustroots/pull/659 — might've been behind this or not. 🤷‍♂️

**Comment by simison** [comment]
Actually looking closer, looks like those were only differences between running `npm i` in Linux vs MacOS.

**Pull request merged**
