### PR TITLE
Update Mocha

### PR DESCRIPTION
**Pull request by simison**
Work-in-progress.

Updates `gulp-mocha` to latest.

Hitting issue with how Mongoose is structured currently.

_Feel free to take over if you're looking for something to work on!_ ;-)

### CODE REVIEW

**Comment by Jagjeet** [comment]
I poked into this and made a little progress on this with regard to loading models, but after that it seems like the configuration is not loading properly. Still trying to investigate what is going on. 

https://github.com/Jagjeet/trustroots/tree/test-framework-deps

**Comment by simison** [comment]
@Jagjeet Nice, I like the approach you took with `file`. Feel free to open a work-in-progress PR!

Here's a bit easier to compare view:

https://github.com/Trustroots/trustroots/compare/master...Jagjeet:test-framework-deps

**Comment by simison** [comment]
@Jagjeet I was looking into this again — did you have a branch running with some changes? Can you open a work-in-progress PR from it? No worries if you don't have time to work on it, others can do it as well but would be ace to have a better starting point than my PR. :-)

**Comment by mrkvon** [comment]
@simison Since we don't use mocha anymore, can this PR be closed? Instead we may remove gulp-mocha completely, i suppose.

**Comment by nicksellen** [comment]
mocha is still used for the server tests. I did look into use jest on the server too, it's not so commonly used for server tests, but it mostly worked to that extent that I tried it. mongoose lib actually [strongly suggests](https://mongoosejs.com/docs/jest.html) that you use mocha instead of jest.

**Comment by mrkvon** [comment]
@nicksellen Thank you for clarifying!

**Pull request closed without merging**
