### PR TITLE
Change license from MIT to AGPL for all new releases of the code.

### PR DESCRIPTION
**Pull request by mariha**
After [Open Source Guides, Legal](https://opensource.guide/legal/) - section 6: What if I want to change the license of my project?

> Switching to a new but compatible license for new releases and contributions is different from relicensing all existing contributions.

> If your project’s existing license is compatible with the license you want to change to, you could just start using the new license. [...] Essentially, with a permissive license the project’s copyright holders have given permission in advance to change licenses.

I've also written to SoftwareFreedom.org foundation to ask if that's ok.

### CODE REVIEW

**Comment by simison** [comment]
Thanks! 

A few more spots need updating:

https://github.com/Trustroots/trustroots/blob/5711b1da0b346a90f5f691e5d9c831ff40c36e6d/modules/pages/client/components/FaqTechnology.component.js#L17

https://github.com/Trustroots/trustroots/blob/939365760cf36bc67c82ebfc50f17e0691a1506e/package.json#L275

https://github.com/Trustroots/trustroots/blob/5711b1da0b346a90f5f691e5d9c831ff40c36e6d/README.md#license

**Comment by mariha** [comment]
Thanks for pointing it out! I looked for all `[^\w]MIT` strings in the codebase and replaced all those that seemed relevant to me.

**Review by simison — APPROVED** [review]
Thank you! I'll merge this and we can continue convo outside the PR if needed.

**Comment by simison** [comment]
Test failures are unrelated, something funky going on:

image

**Pull request merged**
