### PR TITLE
Optimize tribe and message seeding

### PR DESCRIPTION
**Pull request by Jagjeet**
#### Proposed Changes
* Convert tribe and message seeding to ES6
* Add comment blocks to improve file structure
* Improve performance by loading countDocuments() instead of loading entire db structure 
* Add additional comments and modularized code
* Disconnect from the database instead of just exiting

#### Testing Instructions

* Verify tribe seeding and message seeding work as previously 

Fixes #
This is somewhat related to #994 as well, but performance of these scripts was not as bad so the changes ended up being more structural.

### CODE REVIEW

**Comment by Jagjeet** [comment]
The errors here should be resolved once #994 merges. These are the same issues regarding async arrow functions with the `/bin` level eslintrc file. Once we get it resolved there, I will revisit this.

**Comment by simison** [comment]
rebased, eslint issues are gone ☁️  :-)

**Comment by simison** [comment]
Whoooosh! Generating seed data is soooo fast now! 👏

**Comment by Jagjeet** [comment]
Thanks for wrapping this up @simison!

**Pull request merged**
