### PR TITLE
Updates to fix text zoom issue

### LINKED ISSUE #769: tribes/*: overlapping text with big fonts
image

https://www.trustroots.org/tribes/hikers

### PR DESCRIPTION
**Pull request by humphriescarly**
#### Proposed Changes

* Remove position:absolute from .tribe-header-back and restructure the html to allow the page to move down when text is zoomed. 

#### Testing Instructions

* Increase the zoom of the page and the text will no longer clash into each other 

Fixes #769: tribes/*: overlapping text with big fonts

### CODE REVIEW

**Comment by guaka** [comment]
image

To me it looks like it's ready to be merged, but I'm not a CSS wizard like @simison

**Comment by simison** [comment]
Code looks good!

In testing I noticed that backdrop scrolls with the content when it's longer than viewport:

This PR:

screen shot 2018-10-27 at 23 36 05

In `master`:

screen shot 2018-10-27 at 23 35 54

Oddly enough, this doesn't seem to be an issue with mobile where I expect most folks would actually see this issue:

image

Since tribe descriptions aren't that long that on desktop monitors they would cause content scroll, I'd be okay merging this since it's anyway an improvement to previous situation.

Let us know if you'd like to tinker with the backdrop issue, otherwise good to merge! :thumbsup:

I tested using Chrome.

**Comment by humphriescarly** [comment]
Hi @simison,
Good spot - let me tinker and fix that! 
Thank you!

**Comment by humphriescarly** [comment]
HI @simison,
Update made... if you spot anything else let me know.
Thanks!

**Pull request merged**
