### PR TITLE
Update rules

### PR DESCRIPTION
**Pull request by simison**
Update rules people "read" before signup and we refer to when moderating the network.

Screenshot 2020-05-20 at 10 34 58

Screenshot 2020-05-20 at 10 35 01

#### Proposed Changes

See changes here: https://github.com/Trustroots/trustroots/pull/1468/files

* Be explicit about not tolerating objectionable content or abusive users.

See Apple's requirements for including mobile app in their store for context (https://github.com/Trustroots/trustroots-expo-mobile/issues/10#issuecomment-631104166):

> Require that users agree to terms (EULA) and these terms must make it clear that there is no tolerance for objectionable content or abusive users

Anything else we should improve here? @noahsmindfuck @rumwerfer @sitarane @putzenpu @LudoBB Thoughts?

### CODE REVIEW

**Comment by sitarane** [comment]
They don't seem to care that we define "objectionable", which btw makes the whole shebang worthless, but hey, good.

"...clear from spam, ads and objectionable content".

Voila.

**Comment by loberto** [comment]
Maybe from the last line "be yourself...", we could separate the "Be respectful of other" and then add a parenthesis "(meaning no type of abuse will be tolerated)".

And also add a line for asking for money:
"No money involved: no one should ask for money, and no one should offer money for the exchange that happens here"

**Comment by simison** [comment]
Good ideas 👍 Can you help by writing the full final sentences for the first few just so that I understand right?

I'll then update the PR and add the money part.

If the rest of the support folks didn't have objections, we could then deploy these as-is before further additions.

**Comment by loberto** [comment]
I don't feel like the person to do the final phrasing of these rules...  For me, I think I would keep it simple at first.
We could edit the sentence as Sitarane said:
- "...clear from spam, ads and objectionable content".
- "Be yourself, helpful, kind and responsible
- "Respect others and restrain from any kind of abusive behaviour. 
- "Don't ask or accept any form of money exchange for the use of this sire"


this is the best I can do...

**Comment by loberto** [comment]
We should also update them here: https://www.trustroots.org/rules

**Comment by loberto** [comment]
> > We want a world that encourages trust, adventure and intercultural connections. For that to happen through Trustroots we have written down some basic rules that apply to everyone. Please respect these rules:
> 
> Be friendly and know when to stop messaging someone.
> Keep our community clear from spam, ads and objectionable content.
> Be a human being: write messages specifically for their recipient.
> Respect copyrights: stay within your rights if you want to share other people's texts and images - check their legal status!
> Make your own profile. One person, one profile — use your alias or real name; but never impersonate someone else (real or imaginary).
> Be yourself, helpful, kind, responsible.
> Be respectful of others and restrain from any kind of abusive behaviour.
> Our currency is hospitality. Don't ask or accept any form of money exchange for the use of this site. 


> If you ignore these rules, we might stop our services for you without further notice.
> 
> We try to keep our rules simple and we value transparency. We'll update these rules as needed.
> 
> See also our page about privacy.
> 
> Thank you!

**Comment by simison** [comment]
Latest rules text is here: https://github.com/Trustroots/trustroots/blob/master/modules/pages/client/components/RulesText.component.js

**Pull request closed without merging**
