### PR TITLE
Contact List in React

### PR DESCRIPTION
**Pull request by mrkvon**
#### Proposed Changes

- Rewrite Contacts page in React
- add i18n

#### Testing Instructions

Go to `/profile/:username/contacts` and test:
- that the behaviour of contact list didn't change
- that you can filter contacts when there are more than 6 of them
- that you can remove pending contacts

Part of larger migration to React

depends on #1009

### CODE REVIEW

**Comment by mrkvon** [comment]
Travis-CI tests for node v11 fail with
```
NPM dependencies up to date.
npm: 6.5.0-next.0
Error: Wanted npm version >=6.0.0 (>=6.0.0)
To install npm, run `npm install -g npm@>=6.0.0`
```
Annoying. :slightly_frowning_face:

**Comment by simison** [comment]
rebased

**Comment by simison** [comment]
Rebased again after merging https://github.com/Trustroots/trustroots/pull/1009 . :-)

**Comment by simison** [comment]
Just noting that I'm having a bit hard time understanding the file structure here:

- components/ContactListPresentational.js
- components/ContactList.component.js

but let's not that block the PR. :-)

**Comment by simison** [comment]
CI is stuck but I've re-run locally to confirm tests and linters pass.

**Comment by mrkvon** [comment]
> the file structure here

It's an attempt to split the logic part and presentational part into separate components. Does it make sense, or are there pieces which could benefit from refactor?

**Pull request merged**
