### PR TITLE
Admin: improved message list

### PR DESCRIPTION
**Pull request by simison**
#### Proposed Changes

Improve message list for admins:

* Chronological order from oldest to newest
* Just making information more visual:

Before
image

After
Screenshot 2020-12-28 at 17 10 09

#### Testing Instructions

* Open message thread via `/admin/messages`

### CODE REVIEW

**Comment by noahsmindfuck** [comment]
On a user profile
2020-12-28-170838_1920x1080_scrot 

when quering a message thread with <username>
2020-12-28-170717_1920x1080_scrot

**Comment by simison** [comment]
@noahsmindfuck can you try first run `npm ci` and then start the app again with `npm start`? Lemme know if that doesn't help.

**Comment by noahsmindfuck** [comment]
no, it's on a completely fresh install, and I have run npm ci

**Comment by simison** [comment]
@noahsmindfuck I think the second error means that you're not logged in as admin user (403 code is unauthenticated).

About first one I'm still not sure. It does work me locally. Lemme just merge this and you can test it live.

Just curious, what's your browser?

**Comment by noahsmindfuck** [comment]
I am using qutebrowser :) It's a python/qt5 keyboard oriented browser with minimum gui. Very beautiful project ;)

**Pull request merged**
