### PR TITLE
Refactor for arbitrary stats backend

### PR DESCRIPTION
**Pull request by mrkvon**
Realizing #434 .

The code is ready for review. An important thing i need and can't do myself is testing the code with a real stathat account.

## Todo
- [x] the old influxdb tests pass with the new generalized stats api
- [x] write tests for /modules/stats/server/service/stats.server.service.js
- [x] implement the tests (continuously in progress)
- [x] write tests for /.../stathat.server.service.js
- [x] clarify how we deal with time(stamp) in influx.server.service.js. Now the time is ignored. Make tests for valid data for influx.server.service.js.
- [x] what to do with counts from stats API in influxdb? Now stat name is included to measurement name and value is ignored
- [x] refactor influxService to general stats in modules/sparkpost/server/controllers/sparkpost-webhooks.server.controller.js and modules/statistics/server/jobs/daily-statistics.server.job.js
- [x] what should happen when some stat providers are disabled? how to report errors?
- [x] write integration tests for the stats api (send various data and see that it arrived to influx and stathat in a correct format)
- [x] check and write comments and JSDoc
- [x] remove debugging logs from console.
- [x] simplify, review, refactor
- [x] review again, see if the comments in code make sense
- ...

### CODE REVIEW

**Comment by mrkvon** [comment]
The development of this PR is somewhat slow. However, it _might_ work already. There will be more integration tests, comments and refactor in final version (see TODO).

`config/env/local.js` has to have
```
stathat: {
  enabled: true,
  key: '<string>'
}
```
added in order to work (see 'config/env/local.sample.js').

Pushing to `stathat` and `influxdb` is tested to work according to documentation. In reality, not necessarily (not tested with a real stathat account).

So far only pushing message stats works. Daily and sparkpost stats will still push to influxdb only.

**Comment by mrkvon** [comment]
@simison, @chmac, whoever cares:
The PR is ready for review and merge. As i already mentioned, sending metrics to stathat and influx conforms with documentation, but is not tested with real services.
(Almost) everything is tested with automatic tests.
Have a good day.

**Comment by chmac** [comment]
@mrkvon Awesome, thanks for this. I think @simison is out sick at the moment. I'll endeavour to check this out in detail, and once @simison is back online we'll be able to get it merged and deployed.

**Comment by simison** [comment]
:thumbsup: :thumbsup: ✨  and thanks a bunch again @mrkvon !

Sorry it took a while to merge, been extremely busy after I got healthy.

**Pull request merged**
