### PR TITLE
code of conduct

### PR DESCRIPTION
**Pull request by guaka**
straight copy from contributor covenant v1.4

### CODE REVIEW

**Comment by guaka** [comment]
possible improvments:
- [ ] We probably want to refer to https://www.trustroots.org/rules
- [ ] We want to contributors of significant contributions to have a profile on Trustroots, and we (as in board/organisation) probably want to know which profile that is

**Comment by guaka** [comment]
Ah we already had https://github.com/Trustroots/trustroots/blob/master/CONTRIBUTING.md - see #261

**Comment by simison** [comment]
> We want to contributors of significant contributions to have a profile on Trustroots, and we (as in board/organisation) probably want to know which profile that is

That's maybe less code-of-conduct and rather just a protocol / "heads up, please do this" -type of thing somewhere.

I'd suggest we work on _volunteer onboarding_ which is:

- Ask them to read and abide by the code of conduct
- a checklist for things like "make sure to create TR profile and add it to your slack profile", "write an introduction at the slack channel"
- Pointers for people, channels, repositories: where to ask what, who does what, etc
- Some good reading
 
The world is probably full of bots for this purpose (like https://greetbot.io/) that can send a private message to folks who join Slack.

**Comment by Jagjeet** [comment]
> "make sure to create TR profile and add it to your slack profile"

Is it possible to add a field for this in the Slack profile? Not sure how much customization is possible.

**Comment by guaka** [comment]
https://github.com/Trustroots/trustroots/community looks good
image

**Pull request merged**
