### PR TITLE
Prevent api call when rendering tr-location.client directive

### LINKED ISSUE #814: Question mark as a living location crashes the app
Setting "living location" (via https://www.trustroots.org/profile/edit/locations) to contain `?` will cause redirects to login page each time user attempts to edit it again.

This is because the input attempts to load suggestions from Mapbox with URL like:
```
https://api.mapbox.com/geocoding/v5/mapbox.places/?.json?access_...
```

That `/?.json` bit will cause Mapbox API to return 401 unauthenticated and our app thinks _our_ API returned unauthenticated, assuming the user is no more logged in and throws them to the login page.

There are a few fixes around this, any of them will fix this issue but all of them should be made:

- [ ] We shouldn't be querying Mapbox by just rendering those inputs on screen. We should call them only when input actually has changed.
- [ ] We shouldn't query Mapbox with `?` in the value (good to check what happens with `&`, too). - 
- [ ] We shouldn't be querying Mapbox with one character long values at all
- [ ] _Unauthenticated_ interceptor should care only about URLs pointing to our domain, not elsewhere:
    https://github.com/Trustroots/trustroots/blob/15a8bcebee8286eca1591f950a120420b2e08dd3/modules/users/client/config/users.client.config.js#L13-L23

### PR DESCRIPTION
**Pull request by mrtmrtmlck**
#### Proposed Changes

* Preventing api calls when rendering tr-location.client directive

#### Testing Instructions

* Go Edit Profile -> Locations then observe network whether api call occurs or not

Fixes #814

### CODE REVIEW

**Comment by simison** [comment]
Seems like it was there to make this kind of URL query work at search page:

`http://localhost:3000/search?location=London`

Compare what happens in this branch vs at production site.

So this logic just should be moved to search controller(s) in https://github.com/Trustroots/trustroots/tree/master/modules/search/client/controllers

**Comment by mrtmrtmlck** [comment]
> Seems like it was there to make this kind of URL query work at search page:
> 
> `http://localhost:3000/search?location=London`
> 
> Compare what happens in this branch vs at production site.
> 
> So this logic just should be moved to search controller(s) in https://github.com/Trustroots/trustroots/tree/master/modules/search/client/controllers

I've fixed this problem. I hope it is fine. I did my tests and I've some questions as below:

Question 1 (search-map.client.controller.js)
image

Question 2 (tr-location.client.directive.js)
image

**Comment by simison** [comment]
1) `center` seems safer since that's how it has been, although I'd be inclined to test both and see how it behaves for different countries and cities on different zoom levels. I'm assuming the idea of using center by default was to preserve zoom level.

2) I'm not sure if I follow the 2nd question. 


---

BTW you can link lines of code changes like so:

https://help.github.com/articles/getting-permanent-links-to-files/
https://help.github.com/articles/creating-a-permanent-link-to-a-code-snippet/

https://github.com/Trustroots/trustroots/blob/9a3dd5a309e033ff87c1aeb192d785e98867c650/modules/search/client/controllers/search.client.controller.js#L54-L62

Might be easier than screenshots. :-)

**Comment by mrtmrtmlck** [comment]
> 1. `center` seems safer since that's how it has been, although I'd be inclined to test both and see how it behaves for different countries and cities on different zoom levels. I'm assuming the idea of using center by default was to preserve zoom level.
> 2. I'm not sure if I follow the 2nd question.
> 
> BTW you can link lines of code changes like so:
> 
> https://help.github.com/articles/getting-permanent-links-to-files/
> https://help.github.com/articles/creating-a-permanent-link-to-a-code-snippet/
> 
> [trustroots/modules/search/client/controllers/search.client.controller.js](https://github.com/Trustroots/trustroots/blob/9a3dd5a309e033ff87c1aeb192d785e98867c650/modules/search/client/controllers/search.client.controller.js#L54-L62)
> 
> Lines 54 to 62 in [9a3dd5a](/Trustroots/trustroots/commit/9a3dd5a309e033ff87c1aeb192d785e98867c650)
> 
>  if (angular.isDefined(vm.searchQuery) && angular.isString(vm.searchQuery) && vm.searchQuery) { 
>    LocationService.suggestions(vm.searchQuery).then(function (suggestions) { 
>      if (suggestions.length) { 
>        var bounds = LocationService.getBounds(suggestions[0]); 
>        onPlaceSearch(bounds, 'bounds'); 
>        vm.searchQuery = suggestions[0].trTitle; 
>      } 
>    }); 
>  } 
> Might be easier than screenshots. :-)

Thank you :) Below line : https://github.com/Trustroots/trustroots/blob/0ee124f19fa5183039efdc93a0b7a88e541dd9cf/modules/core/client/directives/tr-location.client.directive.js#L98

**Pull request merged**
