### PR TITLE
Rename references route to experiences

### PR DESCRIPTION
**Pull request by simison**
#### Proposed Changes

* Rename `.../references/*` route to `.../experiences/*`

#### Testing Instructions

* Open profile, open references tab
* Click on "write a reference" button

Screenshot 2020-12-21 at 20 47 10

### CODE REVIEW

**Review by hlibbabii — COMMENTED** [review]
Broken link for "Write a reference" on mobile. I guess, should be fixed here?: 

https://github.com/Trustroots/trustroots/blob/a4982d6499bc085d0cea4c9cd80ce52131da7a58/modules/users/client/components/TopNavigationSmall.component.js#L53

**Comment by hlibbabii** [comment]
Also, do we need to fix here?

image

**Comment by simison** [comment]
@hlibbabii Thanks, good finds, fixed in https://github.com/Trustroots/trustroots/pull/1952/commits/6a613a4e6c17e10365250db5ab4ade4968198b45

**Review by hlibbabii — APPROVED** [review]
👍🏼

**Pull request merged**
