### PR TITLE
Add eslint rule for semicolons

### LINKED ISSUE #731: Semicolon rule is not enforced in eslint
Currently, no eslint rule for semicolons is enforced.

Could be fixed with a rule `semi: [2, 'always']` in `.eslintrc.js`.

The rule `always` seems to have existed in the past. Currently it yields less than 10 errors in master.

[related eslint docs](https://eslint.org/docs/rules/semi)

### PR DESCRIPTION
**Pull request by krisgardiner**
Adding a rule to enforce semicolons at the end of line.

Fixes #731

### CODE REVIEW

**Comment by simison** [comment]
Nice!

Looks like changing this brought up the failing files, could you include fixing them in the PR as well? Thanks!

```
modules/core/server/services/push.server.service.js
  19:25  error  Missing semicolon  semi

modules/core/tests/server/core.server.config.tests.js
   39:8  error  Missing semicolon  semi
  166:7  error  Missing semicolon  semi

modules/offers/tests/server/offer-search.server.routes.tests.js
  940:63  error  Missing semicolon  semi

modules/statistics/tests/server/statistics.server.routes.tests.js
  230:56   error  Missing semicolon  semi
  260:150  error  Missing semicolon  semi
  289:150  error  Missing semicolon  semi

modules/offers/client/controllers/offer-meet-list.client.controller.js
  34:10  error  Missing semicolon  semi
```

**Comment by krisgardiner** [comment]
Fixed missing ';' in #737

**Comment by mrkvon** [comment]
@krisgardiner if you push additional commits to your fork's branch `patch-1`, this PR will be updated.

**Comment by simison** [comment]
Next time :-) I merged https://github.com/Trustroots/trustroots/pull/737 so we're good now 👍

**Pull request closed without merging**
