### PR TITLE
Paginate messages module

### PR DESCRIPTION
**Pull request by katsuroo**
Added pagination to message module (frontend + backend)

### CODE REVIEW

**Comment by simison** [comment]
Testing this out now, works really well! Only spotted some small frontend things. I made changes directly to code — summary:
- Add missing express-paginate to package.json
- Instead of Bootstrap Glyphicons, let's try to use Fontawesome. it has better support for different sizes and even [rotations](http://fortawesome.github.io/Font-Awesome/examples/#animated). Actually I've been planning to remove both Glyphicons _and_ Fontawesome from the project and include only font symbols we actually use. (#253)
- Better not to modify generic modules (such as .panel) via CSS. To achieve that padding, you can use .panel-body. Avoid having page specific CSS. 
- No need to add new class for warning text for one place only, these need to be as generic as possible (Bootstrap has [contextual colors](http://getbootstrap.com/css/#helper-classes-colors)).
- vcenter CSS class was probably just some leftover

What's the "Error Portrait" used for: https://github.com/Trustroots/trustroots/pull/267/files#diff-cbd13fe778d7544c0b409f0e5e7c31f5R39 ?

I didn't want to push this anywhere yet so that you could review/test my changes. Here's a patch that you can apply by running `patch -p0 < filename-where-you-save-that-patch`

```
diff --git package.json package.json
index cf7dc2c..17b5b51 100644
--- package.json
+++ package.json
@@ -29,6 +29,7 @@
     "consolidate": "~0.10.0",
     "cookie-parser": "~1.3.4",
     "express": "~4.12.3",
+    "express-paginate": "~0.0.8",
     "express-session": "~1.11.1",
     "forever": "~0.11.0",
     "git-rev": "~0.2.1",
@@ -42,7 +43,7 @@
     "migrate": "~0.2.0",
     "mkdirp": "~0.5.0",
     "mongoose": "~4.0.1",
-    "mongoose-paginate": "^3.1.3",
+    "mongoose-paginate": "~3.1.3",
     "morgan": "~1.5.0",
     "newrelic": "~1.18.2",
     "nodemailer": "~1.3.2",
diff --git public/modules/messages/less/thread.less public/modules/messages/less/thread.less
index e9a9c02..a4fbf5a 100644
--- public/modules/messages/less/thread.less
+++ public/modules/messages/less/thread.less
@@ -233,35 +233,3 @@
     bottom: 0;
   }
 }
-
-// Pagination elements
-.pagination{
-  text-align: center;
-
-  .error-message{
-    font-size: 1.25em;
-    padding: 5px
-  }
-  .panel{
-    padding: 10px;
-  }
-  .glyphicon.glyphicon-user{
-    font-size: 32px;
-  }
-
-  .glyphicon-refresh-animate {
-    -animation: spin .7s infinite linear;
-    -webkit-animation: spin2 .7s infinite linear;
-  }
-  @-webkit-keyframes spin2 {
-    from { -webkit-transform: rotate(0deg);}
-    to { -webkit-transform: rotate(360deg);}
-  }
-  @keyframes spin {
-    from { transform: scale(1) rotate(0deg);}
-    to { transform: scale(1) rotate(360deg);}
-  }
-}
-
-
-
diff --git public/modules/messages/views/thread-messages.client.view.html public/modules/messages/views/thread-messages.client.view.html
index 5ce44a4..150ea43 100644
--- public/modules/messages/views/thread-messages.client.view.html
+++ public/modules/messages/views/thread-messages.client.view.html
@@ -3,9 +3,13 @@
   <div class="row">
     <div class="col-sm-9" id="thread-container">
 
-      <div class="row text-muted text-center" ng-if=" messageHandler.nextPage && messageHandler.resolved === '' "><small>Wait a moment...</small></div>
+      <div class="row text-muted text-center" ng-if=" messageHandler.nextPage && messageHandler.resolved === '' ">
+        <small>Wait a moment...</small>
+      </div>
+
       <!-- Thread -->
       <threads id="messages-thread" ng-style="{width: containerWidth, bottom: replyHeight}" moremessages="moreMessages()">
+
         <!-- Messages -->
         <div class="message"
              id="message-{{ message._id }}"
@@ -14,45 +18,48 @@
              offset="90%"
              up="scroll.up"
              down="scroll.down"
-             ng-class="{ 'message-unread': !messageRead(message, waypoints.scroll.up, waypoints.scroll.down), 'message-pushed' : message.pushed }">
+             ng-class="{ 'message-unread': !messageRead(message, waypoints.scroll.up, waypoints.scroll.down),
+                         'message-pushed' : message.pushed
+                       }">
 
           <!-- Pagination -->
-          <div class="pagination">
-
-          <!-- Error -->
-          <div class="pagination vcenter">
-          <div ng-if="$first && messageHandler.resolved === false && messageHandler.nextPage" class="col-xs-12 col-sm-11">
-            <div class="panel panel-default">
-              <div class="error-message text-muted">
-                Something went wrong :(
+          <div class="pagination text-center">
+
+            <!-- Error -->
+            <div class="pagination">
+              <div ng-if="$first && messageHandler.resolved === false && messageHandler.nextPage" class="col-xs-12 col-sm-11">
+                <div class="panel panel-danger">
+                  <div class="panel-body">
+                    <div class="text-danger">
+                      Something went wrong :(
+                    </div>
+                    <button class="btn btn-warning btn-md" ng-click="moreMessages()">
+                      <span class="fa fa-lg fa-bolt"></span>
+                      Retry
+                    </button>
+                  </div>
+                </div>
               </div>
 
-              <!-- Retry button -->
-              <button ng-click="moreMessages()" class="btn btn-warning btn-md">
-                <span class="glyphicon glyphicon-flash"></span>
-                Retry
-              </button>
+              <!-- Error Portrait -->
+              <div ng-if="$first && messageHandler.resolved === false && messageHandler.nextPage" class="col-sm-1 hidden-xs">
+                <span class="fa fa-2x fa-user message-author avatar"></span>
+              </div>
 
             </div>
-          </div>
+            <!-- /Error -->
 
-            <!-- Error Portrait -->
-            <div ng-if="$first && messageHandler.resolved === false && messageHandler.nextPage" class="col-sm-1 hidden-xs">
-              <span class="glyphicon glyphicon-user message-author avatar"></span>
+            <!-- Loading icon -->
+            <div ng-if="$first && messageHandler.nextPage && messageHandler.resolved !== false" class="text-muted col-xs-12">
+              <i class="fa fa-2x fa-circle-o-notch fa-spin"></i>
             </div>
-          </div>
-          <!-- /Error -->
-
-          <!-- Loading icon -->
-          <div ng-if="$first && messageHandler.nextPage && messageHandler.resolved !== false" class="h3 text-muted text-center col-xs-12 col-sm-12">
-            <span class="glyphicon glyphicon-refresh glyphicon-refresh-animate"></span>
-          </div>
 
           </div>
           <!-- /Pagination -->
 
           <!-- Dividers -->
-          <div ng-if="$first" ng-hide="messageHandler.nextPage" class="divider divider-first col-xs-12"> Conversation started {{ message.created | date:'mediumDate' }}
+          <div ng-if="$first" ng-hide="messageHandler.nextPage" class="divider divider-first col-xs-12">
+            Conversation started {{ message.created | date:'mediumDate' }}
           </div>
 ```

**Comment by simison** [comment]
Oh and I didn't text/touch inbox yet, but same changes could go there. If you're busy with that WP project, I can also merge this and add these changes on top of it?

**Comment by katsuroo** [comment]
@simison Yeah, I realized I didn't save the express paginate and made another commit to add it, but it doesn't look like it got pushed. 

What I tried to do for the error messages was to make it as native as possible. But the results were... questionable... I'm not sure if you checked them out, but for the threads, I made a message panel holding the error message and used a glyphicon as the profile picture ( That is what the error portrait thing is, I thought I changed the name ). On the inbox, I just had it appended to the end of the table.

I tried using the message center , it didn't seem to be good for this use case. After the message is gone there is no indication that an error occurred. The generic colors from bootstrap also looked kind of awkward. So, that's why I decided to do this instead. 

I'm checking the patch code right now.

**Comment by simison** [comment]
Ah okay, explains. Yeah some of the default modules still look crappy (error messages pink background...). I could actually improve their look quickly a bit. 

With message center you can also make persistent messages that don't disappear, but perhaps it's better to show it at right "where" the error happens?

Don't worry too much about these — check the patch and if there's something that you think makes sense, add it to the pile (and at least change the glyphicons to fa, I'll ditch them soon). I'll then merge and look into styles with more time. Now I just had more functional quick look over.

**Comment by simison** [comment]
@katsuroo Tested this out again (also inbox), works well!

Only bugs I found were at inbox; 
- If I set `req.query.limit` low (e.g. 5), I see spinner from the beginning and it doesn't load more threads. With 30 that's unlikely to happen, but with huge screens possible.
- Retry button doesn't work at inbox

Lemme know if you're busy, I can already merge this in that case and we'll look into these later.

**Comment by katsuroo** [comment]
@simison I didn't test the retry button for the inbox since the last refactoring, probably copied and pasted the html from the thread. Just need to pass a param to the controller.

As for the pagination issue, I changed the limit to the default (20) and up the offset of the waypoint to 50%. By increasing the offset, it will solved the problem to some extend but it will also grab 2 pages instead of one on page load now. I think with this it will give reasonable coverage for the devices out there. Might be good to implement this little differently in the future and have the frontend calculate the proper limits for the pagination instead of having a static limit on the backend? I'm not sure how to do that at the moment since there are so many devices out there with vastly different resolutions and zoom level. So I will have to do a bit research into different browser behaviors ( zoom levels etc ) especially on high resolution devices.

Also, I was talking to a friend earlier about this and we think it might be helpful to have a module for error handling, to give more meaningful error messages. Like different error handling for spotty connections , server connection problems and etc. Would likely be useful across the board. 

These things can probably wait but just wanted to put it out there. I'll help you out with the other stuffs first.

**Comment by simison** [comment]
I think for now this is fine, just wanted to hear your opinion. Let's keep observing how it behaves with different screen sizes. I'm sure we'll get back to this stuff once we'll add Socket.io into messages one day (#232).

+1 for error handling module. Also with Socket.io we can easily implement global online/offline state. I like how Trello does this. I tried something [this simple](https://github.com/Trustroots/trustroots/blob/master/public/modules/core/controllers/main.client.controller.js#L9-L17) earlier but it was too irritating.

**Pull request merged**
