### PR TITLE
Update links to instagram page: https://instagram.com/trustroots_org -> https://instagram.com/trustroots

### PR DESCRIPTION
**Pull request by hlibbabii**
#### Testing Instructions

Browse around the website; all links to Instagram should point to https://instagram.com/trustroots now

### CODE REVIEW

**Review by simison — APPROVED** [review]
Thanks!

**Comment by chagai95** [comment]
https://github.com/Trustroots/trustroots/search?q=trustroots_org&type=

I think there are still a few more...

**Comment by simison** [comment]
@chagai95 looks like just one markdown file was left out. Code changes are good, I'll deploy this and markdown can follow separately.

**Comment by simison** [comment]
Updated doc in 7b009f3b

**Pull request merged**
