### PR TITLE
[WIP] Edit host offer - migrate to React

### PR DESCRIPTION
**Pull request by mrkvon**
#### Proposed Changes

* Please do not review, yet. This is very much WIP.

#### Testing Instructions

*

Fixes #

### CODE REVIEW

**Comment by simison** [comment]
Would be great to get this in first https://github.com/Trustroots/trustroots/pull/1156

**Comment by simison** [comment]
https://github.com/Trustroots/trustroots/pull/1156 is in — @mrkvon very interested how you find `Map` component for this. :-)

**Comment by simison** [comment]
I'd probably extract the leaf components (such as the map) into a separate PR and get those in first and then move onto bigger all-encompassing components. That'd limit the size of this PR and make it easier to work with and review. What do you think?

**Comment by mrkvon** [comment]
The branch `offer-host-edit` was reset to `master` and its content is saved in `offer-host-edit-wip`.

**Pull request closed without merging**
