### PR TITLE
[WIP] Add job queue for sending emails

### PR DESCRIPTION
**Pull request by simison**
There was a need to make email delivery more robust, failure safe and easier to test.

**Minus:**
- Adding Queue server introduces yet one more obstacle on getting Trustroots running, but on the other hand installing RabbitMQ seems veeery straightforward (on OSX just `brew install rabbitmq`). Nothing more complicated with Docker compared to current setup. It could be possible to build our own queue script which simply puts jobs to MongoDB, but the complication cost vs time spent building something that's more integrated 

- Worker that picks emails from the queue is a separate instance, but `npm start` now runs both using [concurrently](https://www.npmjs.com/package/concurrently). It might be unclear from which instance stdout/stderr logs are coming from. I clarified it a bit by adding `[worker]`/`[server]` prefixes here and there. Worker could also be just [Agenda](https://github.com/rschmukler/agenda) cron job running at the main instance, but the main instance is being forked to serve more people, so it's not the best place to run these sort of things.

**Plus:**
- Waaaay more robust setup. Easier to just set email aside for sending it later and let application process move forward. In case sending fails, we can try again n times.

- Email handling should anyway be moved to separate services from controllers.

- It will be easier mark bouncing email addresses and thus improve our deliverability.

**Todo:**
- [ ] Handle failures better at signup
- [ ] Remove failing emails from the queue (now it just gets stuck to infinite loop with them)

--- 
Related to #363, #379

### CODE REVIEW

**Comment by nicksellen** [comment]
I'm not sure why Agenda isn't usable for this?

It has a [now](https://github.com/rschmukler/agenda#nowname-data-cb) scheduling time which would save it to db, and run it in a worker right away (the sending email use case). It supports multiple workers connected to the same db (worker locks each job), and has a [reasonable looking ui](https://github.com/joeframbach/agendash).

Getting job management right (retries, errors, visibility, management, etc) correct is fiddly so I would advocate to outsource this to a lib. See all the stuff [kue](https://github.com/Automattic/kue) does beyond just the message queue aspect (kue being another redis-backed option of course, which has a [reasonable looking ui](https://cloud.githubusercontent.com/assets/1458008/5229932/76dd0e70-7716-11e4-9551-e87ce799d8dc.png) too)

I think rabbitmq is ultimately a better solution than polling a mongodb table as Agenda does, but given Agenda is already in place...

At least from the controller perspective it can be implementation agnostic anyway, just an email service method that will send it at some point.

**Comment by simison** [comment]
Hm, could be, it would be simpler setup then. I was initially worried that running such jobs at the main process would be blocking the app, but reading https://github.com/rschmukler/agenda/issues/8 it seems like Agenda handles it pretty well.

**Comment by nicksellen** [comment]
Yes, you can run all the jobs in a totally separate process https://github.com/rschmukler/agenda#multiple-job-processors. It would seem nice to have `server.js` and `worker.js` still though, and they can use node cluster if they want multiple processes.

The node cluster setups on that link [1] are missing _intentional exit_ handling though [2].

[1] https://github.com/rschmukler/agenda/issues/8
[2] https://nodejs.org/api/cluster.html#cluster_worker_exitedafterdisconnect (called _suicide_ in older node versions)

**Comment by nicksellen** [comment]
https://github.com/Trustroots/trustroots/pull/383 is my agenda version

**Pull request closed without merging**
