### PR TITLE
References

### PR DESCRIPTION
**Pull request by simison**
Work-in-progress

### Testing

Adding reference
- Go to another user's profile
- Press "add reference"
- Click through the form

Reading reference
- Go to other user's profile
- Press "references"

Reading your own references
- Go to your profile
- Press "references"

### CODE REVIEW

**Comment by mrkvon** [comment]
I can see that saving references is partially implemented both on server and client side. So far I'm confused about purpose of `/references/` vs `/references-thread/`. I think I can start by writing tests for api CRUD `/references/` and that way I'll figure out what's done and what is missing.

This is my current understanding:
In this step we want users to be able to save and see (type(s) of interaction) + (general recommendation for interacting with people). In the next steps there should be possibility to leave public and private feedback (sort of a freetext reference) and pick (0-3) tribes for the other person.

So far I'll need a feedback on what's correct and incorrect in the above (if it is understandable) and

**Comment by simison** [comment]
`/api/references-thread` serves this little thing that's visible next to message threads for bigger screens:

image

It's completely separate from "user references" (aka just "references").

**Comment by nimish04** [comment]
Pull Request

**Comment by simison** [comment]
Closing this in favor of other PRs: track progress at https://github.com/Trustroots/trustroots/issues/718

**Pull request closed without merging**
